version: 0.2

phases:
  install:
    commands:
      - echo "Installing Apache"
      - apt-get update
      - apt-get install -y apache2
  pre_build:
    commands:
      - echo "Preparing to copy files"
  build:
    commands:
      - echo "Copying index.html to Apache directory"
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo "Creating deployment package"
      - zip -r myapp.zip /var/www/html/index.html appspec.yml stop_apache.sh start_apache.sh install_apache.sh # Adjust paths as necessary
artifacts:
  files:
    - myapp.zip
