version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update 
      - apt-get install -y apache2
      - echo "Preparing to copy files"
  build:
    commands:
      - echo "Copying index.html to Apache directory"
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo "Starting Apache service"
      - service apache2 start

artifacts:
  files:
    - index.html
